services:
  postgres:
    image: postgres:latest
    container_name: shilka-db
    environment:
      POSTGRES_USER: shilka-type
      POSTGRES_PASSWORD: Churka98765
      POSTGRES_DB: shilka-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shilka-type -d shilka-db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shilka-backend
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=shilka-type
      - DB_PASSWORD=Churka98765
      - DB_NAME=shilka-db
      - SECRET_KEY=${SECRET_KEY:-MamaVadimaShalava}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=10080
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/.venv

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: shilka-frontend
    environment:
      - VITE_API_URL=http://localhost:8000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true

volumes:
  postgres_data:
