"""add_themes_table_and_user_theme_field

Revision ID: 068f725b8c7e
Revises: babe6f5d52e5
Create Date: 2025-10-27 15:31:05.346035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '068f725b8c7e'
down_revision: Union[str, Sequence[str], None] = 'babe6f5d52e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('selected_theme_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'themes', ['selected_theme_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'selected_theme_id')
    # ### end Alembic commands ###
