"""add_coin_transaction_model

Revision ID: 55475d42f20c
Revises: 9ce8a91ba1d8
Create Date: 2025-11-01 13:19:40.859525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55475d42f20c'
down_revision: Union[str, Sequence[str], None] = '9ce8a91ba1d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('typing_session_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['typing_session_id'], ['typing_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('typing_session_id')
    )
    op.create_index(op.f('ix_coin_transactions_id'), 'coin_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_coin_transactions_user_id'), 'coin_transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coin_transactions_user_id'), table_name='coin_transactions')
    op.drop_index(op.f('ix_coin_transactions_id'), table_name='coin_transactions')
    op.drop_table('coin_transactions')
    # ### end Alembic commands ###
