"""add_themes_table_and_user_theme_field

Revision ID: 558e9fb3c17b
Revises: 068f725b8c7e
Create Date: 2025-10-27 15:43:03.686996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '558e9fb3c17b'
down_revision: Union[str, Sequence[str], None] = '068f725b8c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
