"""add_settings_bar_settings_to_user

Revision ID: 9ce8a91ba1d8
Revises: e57b2025007a
Create Date: 2025-10-31 21:38:53.759694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ce8a91ba1d8'
down_revision: Union[str, Sequence[str], None] = 'e57b2025007a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # create index if it doesn't already exist (some deployments already have this index)
    op.execute("CREATE INDEX IF NOT EXISTS ix_themes_id ON themes (id)")
    # create FK from themes.author_id -> users.id if not present
    # Alembic's `op.create_foreign_key` does not support IF NOT EXISTS; attempting to create
    # a duplicate FK will raise. We try to create it normally — if this raises in some envs,
    # handle manually or adjust migrations to match the target DB state.
    try:
        op.create_foreign_key(None, 'themes', 'users', ['author_id'], ['id'])
    except Exception:
        # foreign key likely already exists; ignore and continue
        pass
    op.add_column('users', sa.Column('default_time', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('default_words', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('default_language', sa.String(), nullable=True))
    op.add_column('users', sa.Column('default_mode', sa.String(), nullable=True))
    op.add_column('users', sa.Column('default_test_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'default_test_type')
    op.drop_column('users', 'default_mode')
    op.drop_column('users', 'default_language')
    op.drop_column('users', 'default_words')
    op.drop_column('users', 'default_time')
    # Drop FK and index if they exist
    try:
        op.drop_constraint(None, 'themes', type_='foreignkey')
    except Exception:
        pass
    op.execute("DROP INDEX IF EXISTS ix_themes_id")
    # ### end Alembic commands ###
