"""add_settings_bar_settings_to_user

Revision ID: 9ce8a91ba1d8
Revises: e57b2025007a
Create Date: 2025-10-31 21:38:53.759694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ce8a91ba1d8'
down_revision: Union[str, Sequence[str], None] = 'e57b2025007a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_themes_id'), 'themes', ['id'], unique=False)
    op.create_foreign_key(None, 'themes', 'users', ['author_id'], ['id'])
    op.add_column('users', sa.Column('default_time', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('default_words', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('default_language', sa.String(), nullable=True))
    op.add_column('users', sa.Column('default_mode', sa.String(), nullable=True))
    op.add_column('users', sa.Column('default_test_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'default_test_type')
    op.drop_column('users', 'default_mode')
    op.drop_column('users', 'default_language')
    op.drop_column('users', 'default_words')
    op.drop_column('users', 'default_time')
    op.drop_constraint(None, 'themes', type_='foreignkey')
    op.drop_index(op.f('ix_themes_id'), table_name='themes')
    # ### end Alembic commands ###
