"""add_moder_role

Revision ID: b04749779960
Revises: 8ccfeee27cb5
Create Date: 2025-11-10 16:00:36.543771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b04749779960'
down_revision: Union[str, Sequence[str], None] = '8ccfeee27cb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_words_id'), table_name='words', if_exists=True)
    op.drop_index(op.f('ix_words_is_active'), table_name='words', if_exists=True)
    op.drop_index(op.f('ix_words_language'), table_name='words', if_exists=True)
    op.drop_index(op.f('ix_words_language_active'), table_name='words', if_exists=True)
    op.drop_table('words', if_exists=True)
    op.drop_index(op.f('ix_sentences_id'), table_name='sentences', if_exists=True)
    op.drop_index(op.f('ix_sentences_is_active'), table_name='sentences', if_exists=True)
    op.drop_index(op.f('ix_sentences_language'), table_name='sentences', if_exists=True)
    op.drop_index(op.f('ix_sentences_language_active'), table_name='sentences', if_exists=True)
    op.drop_table('sentences', if_exists=True)
    
    # Шаг 1: Убираем default
    op.execute("ALTER TABLE users ALTER COLUMN role DROP DEFAULT")
    
    # Шаг 2: Преобразуем колонку во временный VARCHAR
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE VARCHAR USING role::text")
    
    # Шаг 3: Приводим все значения к нижнему регистру (на случай если есть USER, ADMIN)
    op.execute("UPDATE users SET role = LOWER(role)")
    
    # Шаг 4: Удаляем старый ENUM тип
    op.execute("DROP TYPE IF EXISTS role")
    
    # Шаг 5: Создаем новый ENUM тип с нижним регистром
    op.execute("CREATE TYPE role AS ENUM ('user', 'moder', 'admin')")
    
    # Шаг 6: Преобразуем колонку обратно в ENUM
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE role USING role::text::role")
    
    # Шаг 7: Устанавливаем новый default
    op.execute("ALTER TABLE users ALTER COLUMN role SET DEFAULT 'user'::role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('user', 'moder', 'admin', name='role'),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
    
    # Удаляем ENUM тип
    role_enum = postgresql.ENUM('user', 'moder', 'admin', name='role', create_type=False)
    role_enum.drop(op.get_bind(), checkfirst=True)
    
    op.create_table('sentences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('word_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sentences_pkey'))
    )
    op.create_index(op.f('ix_sentences_language_active'), 'sentences', ['language', 'is_active'], unique=False)
    op.create_index(op.f('ix_sentences_language'), 'sentences', ['language'], unique=False)
    op.create_index(op.f('ix_sentences_is_active'), 'sentences', ['is_active'], unique=False)
    op.create_index(op.f('ix_sentences_id'), 'sentences', ['id'], unique=False)
    op.create_table('words',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('words_pkey'))
    )
    op.create_index(op.f('ix_words_language_active'), 'words', ['language', 'is_active'], unique=False)
    op.create_index(op.f('ix_words_language'), 'words', ['language'], unique=False)
    op.create_index(op.f('ix_words_is_active'), 'words', ['is_active'], unique=False)
    op.create_index(op.f('ix_words_id'), 'words', ['id'], unique=False)
    # ### end Alembic commands ###
