"""add typing_sessions table

Revision ID: b545a4fcf7fc
Revises: b971d26a06a7
Create Date: 2025-10-02 00:01:13.397961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b545a4fcf7fc'
down_revision: Union[str, Sequence[str], None] = 'b971d26a06a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('typing_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wpm', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('words', sa.Text(), nullable=False),
    sa.Column('history', sa.Text(), nullable=False),
    sa.Column('typing_mode', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_typing_sessions_id'), 'typing_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_typing_sessions_user_id'), 'typing_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_typing_sessions_user_id'), table_name='typing_sessions')
    op.drop_index(op.f('ix_typing_sessions_id'), table_name='typing_sessions')
    op.drop_table('typing_sessions')
    # ### end Alembic commands ###
