"""add new column shilka_coins

Revision ID: b971d26a06a7
Revises: 5afaf45d7792
Create Date: 2025-10-01 19:47:37.177296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b971d26a06a7'
down_revision: Union[str, Sequence[str], None] = '5afaf45d7792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('shilka_coins', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'shilka_coins')
    # ### end Alembic commands ###
