"""removed_double_shilka_coins

Revision ID: ba5cfc9ab1b1
Revises: 55475d42f20c
Create Date: 2025-11-02 01:02:54.571982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba5cfc9ab1b1'
down_revision: Union[str, Sequence[str], None] = '55475d42f20c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
