"""fix_user_theme

Revision ID: d09f42b69f1d
Revises: ba5cfc9ab1b1
Create Date: 2025-11-02 01:04:49.790028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd09f42b69f1d'
down_revision: Union[str, Sequence[str], None] = 'ba5cfc9ab1b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
