"""add_themes_table_and_user_theme_field_fix

Revision ID: e57b2025007a
Revises: 558e9fb3c17b
Create Date: 2025-10-27 15:57:04.096956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e57b2025007a'
down_revision: Union[str, Sequence[str], None] = '558e9fb3c17b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
