name: Main Branch CI

on:
  push:
    branches:
      - main

jobs:
  quick-check:
    name: Quick Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Run frontend tests
        working-directory: ./frontend
        run: npm test -- --run

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3

      - name: Install backend dependencies
        working-directory: ./backend
        run: poetry install --no-interaction

      - name: Notify success
        if: success()
        run: echo "✅ All checks passed on main branch!"
